version: '3.4'

services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: src/Products.API/Dockerfile
    depends_on:
      - products.db
  
  products.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "sTr0nGpaSSw0Rd"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'